name: Publish Package
on:
  push:
    branches:
      - master
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@sparkle'
      - name: Install Dependencies
        run: yarn
      - name: Publish Core
        run: yarn core publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}